general {
    lock_cmd = pidof hyprlock || hyprlock --immediate
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 150 # 2.5 min
    on-timeout = brightnessctl -s s 10% && brightnessctl -d dell::kbd_backlight -s s 0%
    on-resume = brightnessctl -r && brightnessctl -d dell::kbd_backlight -r
}

listener {
    timeout = 300 # 5 min
    on-timeout = loginctl lock-session
}

listener {
    timeout = 330 # 5.5 min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 480 # 8 min
    on-timeout = systemctl suspend
}
