# A collection of aliases
alias notes="cd ~/notes"
alias shelf="cd ~/shelf"
alias confs="cd ~/.config"
alias proj="cd ~/projects"
alias tri="cd /home/pano/projects/tricritical-ising"
alias tasks="xdg-open 'https://github.com/users/PanosEconomou/projects/3'"
alias def="cd ~/projects/Defuse/"

alias rebash="source ~/.bashrc"
alias battery="upower -i \$(upower -e | grep -i BAT) | grep --color=never -E 'state|to full|to empty|percentage'"
alias clip="wl-copy"
alias bat="battery"
alias printers="xdg-open http://localhost:631/"
alias la="ls -la"
alias code="/usr/bin/code --enable-proposed-api ms-toolsai.jupyter"
alias vi="nvim"
alias eba="source env/bin/activate"

# Nix specific aliases
alias renix="sudo nixos-rebuild switch --flake ~/.nixos#\$(hostname)"
alias vhome="vi ~/.nixos/hosts/\$(hostname)/home.nix"
alias vsys="vi ~/.nixos/hosts/\$(hostname)/system.nix"
alias cmodules="cd ~/.nixos/modules"
alias cnix="cd ~/.nixos"
alias nsh="nix-shell"

# A collection of functions that act as aliases
function t() {
	typora --enable-features=UseOzonePlatform --ozone-platform=wayland "$@" &
	disown
}

function o() {
	xdg-open "$@" &
	disown
}

function open() {
	xdg-open "$@" &
	disown
}

low() {
  for file in "$@"; do
    # Skip if it's a directory
    [ -f "$file" ] || continue
    # Generate the new filename
    new_name=$(echo "$file" | tr ' ' '-' | tr '[:upper:]' '[:lower:]')
    # Rename the file
    mv "$file" "$new_name"
  done
}

gcm() {
	git commit -m "$*"
}

gcma() {
	git add --all
	git commit -m "$*"
	git push origin main
}

yy() {
    "$@" | clip;
}
